aspnet/Universe

build/_k-standard-goals.shade
- skip a few targets when src directory does not exist
/cc Universe triage team
=> #37, Support sample- or test-only repositories

makefile.shade
=> Fixing issue that pushes nuget.config to release

build/_k-standard-goals.shade, build/_kpm-local-publish.shade
Changes to allow using kpm-publish to publish packages to CI volatile directory. 
Incorporates https://github.com/aspnet/Universe/pull/148
=> Ci publish

makefile.shade
Fixes https://github.com/aspnet/Universe/issues/160
cc @pranavkm
=> Environment variable to specify the build branch

build-template/build.cmd, build/_k-test.shade
1. SKIP_KVM_INSTALL => SKIP_DNX_INSTALL
2. Update k test
@NTaylorMullen @ChengTian @Eilon @muratg
=> Futher renaming work

NuGet.Config
fixes https://github.com/aspnet/Universe/issues/174
=> Renaming Nuget.org feed key name to Nuget

build-template/NuGet.Config, build-template/NuGet.master.config, build-template/NuGet.release.config
https://github.com/aspnet/Universe/issues/174
=> Renaming Nuget.org feed key name to Nuget in config templates.

build/dnvm.ps1, build/dnvm.sh
=> Integrate latest dnvm

build/dnvm.ps1, build/dnvm.sh
=> Update dnvm to build 10345

build-template/build.sh, build.sh, build/_k.shade
https://github.com/aspnet/dnx/issues/1473
@davidfowl @muratg
=> Remove k command and use dnx instead

build/_k-standard-goals.shade
Currently Helios won't build on machines that don't have VS2013 installed (only VS2015)
=> Enabling MSBuild 14 in the default native-compile target

build/_k-test.shade
Update to address cross-platform CI issues with EntityFramework SqlServer tests
@pranavkm @victorhurdugaci
=> Support single threaded running of specific test projects through environment

build/_k-standard-goals.shade
- not currently cleaning in most cases
- typo in 16bb0df
=> Fix `target-dir-clean` target

build/_k-standard-goals.shade
rimraf needs to pull node.js and is slow.
=> Replacing rimraf in target-dir-clean with non-node.js based solution

build/dnvm.ps1
React to https://github.com/aspnet/dnx/issues/1572
=> React to renaming "k-crossgen.cmd" to "dnx-crossgen.cmd"

build/dnvm.ps1, build/dnvm.sh
@muratg 
One step missing from https://github.com/aspnet/Universe/pull/223
Turns out only version numbers need to be updated.
=> Update dnvm scripts

makefile.shade
=> Remove the WebSocketAbstractions repo.

build/_k-standard-goals.shade, build/_kpm-build.shade, build/_kpm-pack.shade
=> Fix argument parsing for fast build

makefile.shade
=> Added Localization repo to makefile

makefile.shade
Add the ability to include/exclude certain repos when building universe
cc @pranavkm @BrennanConroy @troydai
=> Add the ability to specify what repos to include/exclude while building 

build/_k-standard-goals.shade
Naming suggestions welcome :smiley: 
@pranavkm @Eilon
=> Added a target to verify nupkgs with NugetPackageVerifier

build/_k-standard-goals.shade
cc @pranavkm @troydai @BrennanConroy
=> Build tests and samples during regular build

makefile.shade
=> Add BrowserLink

build.cmd, build/BuildEnv.shade, build/_k-standard-goals.shade, makefile.shade
=> Updating to Sake 0.2.2

build/_k-standard-goals.shade
=> Added Nuget feed and renamed packagelist json

build/_k-standard-goals.shade
=> Moving nuget-verify to run before test

build/dnvm.ps1, build/dnvm.sh
- `beta8-15518` to `rc1-15523`
- main changes include
- remove `-a` alias for `-alias`; `build.cmd` files updated (thanx @NTaylorMullen)
- [Linux] deprecate `dnvm unalias`; add `dnvm alias -d`
- add `dnvm uninstall`
=> Update to latest `dnvm`

KoreBuild-dotnet/build/_dnx-test.shade, KoreBuild-dotnet/build/_dnx.shade, KoreBuild-dotnet/build/_dotnet-publish.shade, KoreBuild-dotnet/build/_k-standard-goals.shade
Run tests with the new runner on CoreCLR. Run with dnx on desktop.
Please review: @BrennanConroy @anurse 
FYI @piotrpMSFT
=> Support for dnx test (coreclr only)

build-template-dotnet/build.cmd
=> Fix path in build-template-dotnet

KoreBuild-dotnet/build/_dotnet-test.shade
=> Add test args to dotnet-test-xunit

build/_k-standard-goals.shade
Related to https://github.com/aspnet/DnxTools/pull/15
@pranavkm or @Eilon
=> Removed use of dnu commands

KoreBuild-dotnet/build/KoreBuild.cmd, KoreBuild-dotnet/build/KoreBuild.sh, KoreBuild-dotnet/build/_xunit-test.shade
Required for loading the binding redirects for test dlls
cc @pranavkm
=> Install xunit.core

KoreBuild-dotnet/build/_k-standard-goals.shade
Turns out we're not building tests and samples anymore
cc @pranavkm @Tratcher
=> Build tests and samples

KoreBuild-dotnet/build/KoreBuild.cmd, KoreBuild-dotnet/build/KoreBuild.sh
Skip runtime install option
cc @pranavkm @BrennanConroy
=> Skip runtime install flag

KoreBuild-dotnet/build/_k-standard-goals.shade
=> Fix odd bug in globbing

KoreBuild-dotnet/build/KoreBuild.sh
=> Set DOTNET_HOME correctly.

KoreBuild-dotnet/build/_dotnet-test.shade, KoreBuild-dotnet/build/_k-standard-goals.shade
=> Enable running tests using dotnet xunit test runner

KoreBuild-dotnet/build/_k-standard-goals.shade
=> Fix cross gen issue

tools/PinVersion/project.json
=> Updated Json.Net version

KoreBuild-dotnet/build/_dotnet-publish.shade
=> Fix dotnet publish to only delete the specific framework bin folder

KoreBuild-dotnet/build/_xunit-test.shade
Also publishes to obj/ instead of .testpublish/
cc @JunTaoLuo @pranavkm
=> Execute tests for net451 and/or dnx451

KoreBuild-dotnet/build/_dotnet-test.shade, KoreBuild-dotnet/build/_k-standard-goals.shade, KoreBuild-dotnet/build/_xunit-test.shade
Fixes https://github.com/aspnet/Universe/issues/389
cc @pranavkm @tushargupta51
=> Pass the correct configuration to the test runners

KoreBuild-dotnet/build/KoreBuild.sh
between what the build runs vs what project references
Also removing for Sake since it is not needed
=> Removing -pre as it causes test failures due to version mismatch

KoreBuild-dotnet/build/_dotnet-test.shade
@natemcmaster @victorhurdugaci @pranavkm
=> Enable passing in 'parallel' parameter to dotnet test

KoreBuild-dotnet/build/_k-standard-goals.shade
=> Use Dotnet to run tests for DNXCore50

makefile.shade
=> Attempt to use non cross gened csc.exe

makefile.shade
Fixes https://github.com/aspnet/Coherence-Signed/issues/182
- Run tests without sources
- Remove some old dead code
- Update repo names
- Allow the build to sync repos to particular commits
cc @cesarbs @pranavkm
=> Test packages and don't rebuild sources

makefile.shade
=> Set UNIVERSE_COMMITS_FILE env. variable after caching Coherence.

makefile.shade
=> Cache Coherence in the correct place.

makefile.shade
=> Add a way to exclude repositories from having the src folder deleted

makefile.shade
#423
#425
cc @victorhurdugaci @pranavkm
=> Delete previous Coherence cache and expand packages (#423, #425).

makefile.shade
@pranavkm 
https://github.com/aspnet/KestrelHttpServer/pull/731
=> Add libuv-package repo

makefile.shade
=> Properly set commits file location after caching Coherence.

makefile.shade
=> Add MvcPrecompilation

makefile.shade
=> Add AzureIntegration repo

makefile.shade
=> Don't delete the 'src' folder for VS2017 solutions

makefile.shade
=> Add Identity Service to Universe

build.ps1, build/repo.props, build/repo.targets, makefile.shade
React to https://github.com/aspnet/KoreBuild/pull/180
=> Update Universe to use the MSBuild-first KoreBuild

build/RepositoryBuild.targets
Possibly fixes https://github.com/aspnet/Universe/issues/481
=> Enable UnloadProjectsOnCompletion to prevent OOM

build/repo.targets
React to aspnet/BuildTools#199
:watch: CI
=> Remove usage of XmlPoke2

build/RepositoryBuild.targets, build/repo.targets
Related PR https://github.com/aspnet/BuildTools/pull/214
=> Using PackagePublisher tool to publish packages as it does retries

build/repo.targets
Resolves https://github.com/aspnet/KoreBuild/issues/216
Depends on https://github.com/aspnet/BuildTools/pull/239
=> Resolve warnings about duplicate imports of Microsoft.Common.targets

build/Repositories.props
Part of aspnet/PlatformAbstractions#50
=> Remove Microsoft.Extensions.PlatformAbstractions

build/Repositories.props
=> Remove Entropy from Universe builds

build/RepositoryBuild.targets, build/tasks/Logger/DefaultPrefixMessageWriter.cs, build/tasks/Logger/FlowLogger.cs, build/tasks/Logger/IWriter.cs, build/tasks/Logger/TeamCityMessageWriter.cs
=> Add flow logger to help with console output parallelism

build/repo.beforecommon.props
React to https://github.com/aspnet/BuildTools/pull/309
=> Set IncrementalVersion=true

build/dependencies.props
Using the latest version, though I haven't really tested with this yet.
=> Add 2.0.1 NETCore.App

build/Repositories.props, build/RepositoryBuild.targets, build/dependencies.props, build/repo.targets, build/tasks/GeneratePackageVersionPropsFile.cs, build/tasks/RepoTasks.tasks
This should allow us to override RuntimeFrameworkVersion automatically based on TFM.
=> Generate the package version props file

build/repo.targets, build/tasks/CopyPackagesToSplitFolders.cs, build/tasks/Utilities/PackageCategory.cs
=> Copy symbol packages to artifacts/symbols

build/RuntimeStore.targets, build/artifacts.props, build/common.props, build/dependencies.props, build/tasks/AddMetapackageReferences.cs
=> Fix the metapackage generation

build/RuntimeStoreInstaller.targets, build/tools/packaging/hosting_debian_config.json
This will resolve https://github.com/aspnet/Universe/issues/605 as well as fix a bug in the rpm installer summaries.
=> Installer generation updates

build/PackageArchive.targets
Last artifact that we have to manually rename.
=> Revert to old lzma name scheme

build/artifacts.props
Add the new sources package in `Routing`.
cc @rynowak @ryanbrandenburg
=> Add Microsoft.AspNetCore.Routing.UrlMatchingTree.Sources package

build/dependencies.props
=> Update corefxlab packages

build/tasks/AnalyzeBuildGraph.cs
Depends on https://github.com/aspnet/EntityFrameworkCore/pull/10553.
cc @ryanbrandenburg
=> Re-enable the version consistency check

build/SharedFx.props, build/SharedFx.targets, build/SharedFxInstaller.targets
Addresses: https://github.com/aspnet/Universe/issues/757
=> Generate cumulative archives for all platforms

build/Publish.targets, build/SharedFx.targets, build/repo.props, build/repo.targets, build/tasks/PublishToAzureBlob.cs, build/tasks/RepoTasks.csproj, build/tasks/RepoTasks.tasks, version.props
- Add PublishToAzureBlob task
- Move badge/version txt file generation to publish step
cc @muratg @JunTaoLuo
=> Add targets to deploy all known installers to an azure blob feed

build/artifacts.props
=> Remove Dispatcher packages

.appveyor.yml, .travis.yml, build/RuntimeStoreInstaller.targets, build/artifacts.props, build/dependencies.props, build/submodules.props, korebuild-lock.txt, scripts/PatchVersionPrefix.ps1, src/Microsoft.AspNetCore.All/build/aspnetcore-store-2.0.5.xml, version.props
Updates the 2.0.x build to include patch changes to Kestrel and EF Core.
cc @Eilon
=> Start work to prepare next 2.0.x patch

build/artifacts.props, build/dependencies.props, build/submodules.props, korebuild-lock.txt, korebuild.json, scripts/PatchVersionPrefix.ps1, scripts/common.psm1
This includes a bunch of scripted updates to repos to apply cascading versions
cc @Eilon @muratg
=> Update FileSystem submodule and apply the result of the cascading version

build/SharedFx.props, build/SharedFx.targets, build/artifacts.props, build/repo.targets, build/tasks/AddMetapackageReferences.cs, build/tools/templates/SharedFx/SharedFx.csproj, src/Microsoft.AspNetCore.App/Microsoft.AspNetCore.App.csproj, src/Microsoft.AspNetCore.App/build/netcoreapp2.1/Microsoft.AspNetCore.App.props
Addresses https://github.com/aspnet/Universe/issues/721.
Potentially significant refactoring needed since it conflicts heavily with https://github.com/aspnet/Universe/issues/721.
=> Produce .App metapackage and shared framework

build/SharedFx.targets, build/artifacts.props, build/repo.targets, build/tasks/AddMetapackageReferences.cs, src/Microsoft.AspNetCore.All/Microsoft.AspNetCore.All.csproj
Remove BrowserLink from Microsoft.AspNetCore.App
Addresses #836 https://github.com/aspnet/Universe/issues/820. 
Note @pranavkm this would mean that we can revert https://github.com/aspnet/Mvc/pull/7253. 
cc @muratg @Eilon
=> Flatten dependencies of Microsoft.AspNetCore.All metapackage

build/artifacts.props, build/dependencies.props
This is a new package that's shipping out of band. We're now merging it into the patch branch for long term servicing. If 2.0.6 re-spins then we'll include it.
I'll update the submodule once we confirm if this is going into 2.0.6.
=> [2.0.x] Add new WsFederation package and dependencies

build/artifacts.props, build/repo.targets, build/tasks/AddArchiveReferences.cs
This should prevent unhelpful messages like [this](http://aspnetci/viewLog.html?tab=buildLog&logTab=tree&filter=debug&expand=all&buildId=400608&_focus=333).
=> Notify which package is missing

README.md, build/SharedFxInstaller.targets, build/repo.props
Addresses https://github.com/aspnet/Universe/issues/866
=> Rename generic rpm installers

build/Publish.targets, build/SharedFx.props, build/SharedFx.targets, build/repo.props, build/tools/templates/SharedFxSymbols/SharedFrameworkSymbols.nuspec
Addresses https://github.com/aspnet/Universe/issues/853
Checking effects on downstream builds.
=> Create aspnetcore shared framework symbols packages

build/artifacts.props
Resolves https://github.com/aspnet/Universe/issues/873
=> [2.1.0-preview1] Mark Microsoft.AspNetCore.AspNetCoreModule as shipping

build/artifacts.props
Part of https://github.com/aspnet/EntityFrameworkCore/pull/11206
=> Rename Microsoft.EntityFrameworkCore.Attributes to Microsoft.EntityFrameworkCore.Abstractions

build/artifacts.props
This changed deleted this package https://github.com/aspnet/SignalR/commit/6a8ede07701c82bbebb91d55a6d1dc5a42b129ee
=> Remove Microsoft.AspNetCore.Sockets

build/artifacts.props
=> Ship Microsoft.EntityFrameworkCore.Analyzers

build/artifacts.props
Part of aspnet/EntityFrameworkCore#10554
=> Make dotnet-ef a global tool

build/artifacts.props
=> Add Azure AD B2C integration package

build/dependencies.props
Resolves #993 
@Eilon i'm assuming you will take care of OSS approval?
=> Update to Newtonsoft.Json 11.0.2

build/artifacts.props
No clue if this will work... but it's what people told me to do ;)
=> update artifacts.props in dev

scripts/GenerateTags.ps1, scripts/common.psm1
Update the generate tags script to produce a .csv file with commit sha, repo, and tag name.
FYI @danroth27
=> Generate a .csv file containing tag information

build/dependencies.props
https://github.com/aspnet/Common/pull/337
https://github.com/aspnet/Common/pull/335
Would need to go in with it.
=> Update corefx to 2.1.0-preview3-26413-01

build/artifacts.props
=> react to aspnet/SignalR#2005

build/dependencies.props
Workaround #1090 
FYI @muratg - this change reflects what a ProdCon build would do automatically.
=> Update dependencies to ProdCon build 20180423-01-1621379

build/artifacts.props
cc @muratg This is escrow resetting.
=> Include .App in LZMA ... again

version.props
Bump the framework version to 2.1.0-rtm
TODO before merging:
=> Set version to 2.1.0-rtm

build/artifacts.props, build/dependencies.props
https://github.com/aspnet/Universe/issues/1108
https://github.com/aspnet/Universe/issues/1129
=> Make AzureKeyVault.HostingStartup shipping and update dependency version

build/dependencies.props
https://github.com/aspnet/Universe/issues/1108
=> Update AzureServicesAppAuthentication to 1.0.1

build/artifacts.props
Reaction PR for https://github.com/aspnet/EntityFrameworkCore/pull/12019
Will roll forward EF submodule on merge.
=> Remove Cosmos.Sql from dev

build/artifacts.props, build/external-dependencies.props, build/submodules.props
I missed this repo when preparing the original list of repos patching in 2.1.1
=> Add Razor to the list of patching repos

build/dependencies.props
Addresses https://github.com/aspnet/Universe/issues/1170. Not merging for now and waiting for approval.
=> Update WebApi.Client package version

build/artifacts.props
Adding Microsoft.AspNetCore.SignalR.Specification.Tests
=> Adding Microsoft.AspNetCore.SignalR.Specification.Tests

build/RepositoryBuild.targets, korebuild-lock.txt
Part of https://github.com/aspnet/Coherence-Signed/issues/784
Depends on https://github.com/aspnet/BuildTools/pull/688
=> Gather and merge sign requests from repo builds

Directory.Build.props, Directory.Build.targets, Microsoft.AspNetCore.sln, build/SharedFx.targets, build/common.props, build/dependencies.props, build/tasks/RepoTasks.csproj, build/tools/templates/Archive/Archive.csproj, build/tools/templates/SharedFx/SharedFx.csproj, src/Directory.Build.props, src/Microsoft.AspNetCore.All/Microsoft.AspNetCore.All.csproj, src/Microsoft.AspNetCore.Analyzers/Microsoft.AspNetCore.Analyzers.csproj, src/Microsoft.AspNetCore.App/Microsoft.AspNetCore.App.csproj, test/SharedFx.UnitTests/AssertEx.cs, test/SharedFx.UnitTests/SharedFx.UnitTests.csproj, test/SharedFx.UnitTests/SharedFxTests.cs, test/SharedFx.UnitTests/TestData.cs, test/SharedFx.UnitTests/TestDataAttribute.cs, version.props
I'm preparing some work soon that will affect the way we generate the shared framework. Adding tests now ahead of time to ensure refactoring preserves expected output.
TODO (in follow-up PRs)
~~* Automate these tests to run against actual build output~~
* Add more coverage
cref https://github.com/aspnet/Universe/issues/706
cc @mikeharder @JunTaoLuo
=> Begin to add unit tests for the shared framework

build/artifacts.props
This should wait until https://github.com/aspnet/SignalR/pull/2451 is merged
=> Adding Microsoft.AspNetCoreSignalR.Specification.Tests

build/artifacts.props, build/dependencies.props, build/external-dependencies.props, build/repo.targets, build/sources.props, build/submodules.props, scripts/PatchVersionPrefix.ps1, version.props
Reset the artifacts shipping for the next 2.1.x patch.
FYI @mmitche @muratg
=> Prepare 2.1.2 patch

.gitignore, build/RuntimeStoreInstaller.targets, scripts/UploadBlobs.ps1, scripts/common.psm1
Let's stop doing this by hand.
TODO:
How can we reliably also fetch the assets for the preview 2.0 build? At the moment, I've been manually copying them. Thoughts @JunTaoLuo ?
=> [2.0] Add script used to deploy blobs to Azure storage

build/dependencies.props, build/external-dependencies.props
Needed for https://github.com/aspnet/KestrelHttpServer/pull/2653
=> Add AspNetCore.Testing.H2Spec.All dependency

build/dependencies.props
Addresses: https://github.com/aspnet/Universe/issues/1223. Will be merging this to release dev as well as the msrc branches upon approval.
=> Update DotnetArchive version

build/dependencies.props
Addresses #https://github.com/aspnet/Caching/issues/396
=> Update StackExchange.Redis.StrongName version

.appveyor.yml, .gitmodules, .travis.yml, README.md, korebuild.json, run.ps1, scripts/UpdateDependenciesCoreFx.ps1, scripts/update_travis_appveyor_yml.py
Part of https://github.com/aspnet/Home/issues/3278
Master branches have been created on all repos, set to default, and enabled branch protection.
=> Change default branch to master

build/artifacts.props
https://github.com/aspnet/IISIntegration/pull/1037#pullrequestreview-136455441
=> Add Microsoft.AspNetCore.Server.IntegrationTesting.IIS

build/dependencies.props, build/external-dependencies.props
Needed by aspnet/EntityFrameworkCore#12988
=> Add NetTopologySuite external dependency

build/artifacts.props
Added in aspnet/EntityFrameworkCore#13115
=> Add Microsoft.EntityFrameworkCore.SqlServer.NetTopologySuite

build/artifacts.props
Note that I marked the ItemTemplates as `ship` as well.
=> Start shipping templates to NuGet

build/artifacts.props
Marking this as ship, but not adding to metapackages or shared frameworks.
React to https://github.com/aspnet/DataProtection/pull/323
=> Add Microsoft.AspNetCore.DataProtection.EntityFrameworkCore

build/dependencies.props
These lines shouldn't have been removed.
=> Fix merge of 2.1->2.2

build/dependencies.props, scripts/UpdateRepos.ps1
=> Merge release/2.2 to master

build/dependencies.props
Fix for https://github.com/aspnet/Universe/issues/1098
@natemcmaster
=> Update IdentityModel to 5.3

build/dependencies.props, build/external-dependencies.props
=> Add NetTopologySuite.IO.SqlServerBytes dependency
