aspnet/Universe

build/_k-build.shade
build/_k-standard-goals.shade

Under Linux building KRuntime a second time fails with 
```
Copy From: [...]/src/klr.host/bin/Debug/aspnet50/*.*
To: [...]/src/klr.host/../../artifacts/build/KRE-CLR-x86/bin
cp: cannot stat '[...]/src/klr.host/bin/Debug/aspnet50/*.*': No such file or directory
```
There is a `bin/debug` folder though.

Fix the casing of the configuration

---

build/_k-standard-goals.shade
build/_kpm-pack.shade

parent: https://github.com/aspnet/XRE/issues/967
@davidfowl , I keep the `k-build` goal and add a new goal `k-pack`. `k-build` invokes `kpm build`, while `k-pack` invokes `kpm pack`.
Tested this change by doing `build verify` in this branch https://github.com/aspnet/XRE/pull/1124

React to renaming "kpm build" to "kpm pack"

---

build/_bower.shade
build/_grunt.shade
build/_k-standard-goals.shade
build/_node-install.shade
build/_node.shade
build/_npm.shade

As the commits say:
- include `bower` and `npm` commands in `--quiet` target
- short-circuit `TestCommand()` calls once commands are installed locally
/cc @davidfowl

Quiet builds a bit more

---

build/_node-install.shade
build/_npm.shade

- #144
- problems seem primarily to occur when `node` is globally installed but a
package (`grunt` or `bower`) is not; `npm install X` fails in this case
- create the `--prefix` directory first to avoid these installation failures

Create target directory for `npm` installations

---

build/_bower.shade
build/_grunt.shade
build/_k-standard-goals.shade
build/_node-install.shade

- don't confuse leftover folders with local presence of `bower` or `grunt-cli` libraries
- get `run-grunt` working on Linux machines when `grunt-cli` is installed globally
- don't clean up `node_modules` folders on every build; speed up `npm install`

Make `bower`, `grunt`, and `npm` commands a bit faster and more reliable

---

build/_bower.shade
build/_grunt.shade
build/_npm.shade
build/_rimraf.shade
build/_verify-authenticode.shade

- aspnet/Mvc#2082
- problems specific to local `node` and related installations
- quote authenticode verification target
- quote local `node` library paths
- quote local `npm.cmd` path (with ye olde `/S` double-quoting hack)
- quote `--prefix` values in `npm install` commands
- quote `rimraf` directories to delete

Fix build failures when source is under a directory with spaces in the name

---

makefile.shade

The XPlat build hangs because git waits for user input. Added a flag that will not invoke git if credentials are not available.
@NTaylorMullen @troydai @ChengTian @suhasj

Skip credentials prompt for CI builds

---

build/_k-restore.shade
build/_kpm-build.shade
build/_kpm-pack.shade
build/_kpm-publish.shade

parent https://github.com/aspnet/Universe/issues/186
@davidfowl @muratg 
Following the gradual adoption strategy. Only rename the kpm inside standard goal scripts, so nothing will be broken.
I see we still have standard goals with names like `_k-restore.shade` and `_kpm-build.shade`. We may want to replace `k` with `dnx` and replace `kpm` with `dnu` later.

Rename kpm to dnu in standard goal scripts

---

build/BuildEnv.shade
build/_k-standard-goals.shade

This change is to set an environment variable for the AssemblyFileVersion attribute. 
The version has 5 characters, the first 3 are the number of months since 2015/1/1 and the last 2 are the day of the month. @joeloff suggested this format since it is used in other places. For example, today's version is 00327.
Please review: @joeloff @pranavkm 
@Eilon, @davidfowl are you okay with the version in this format?
There is a DNX change coming soon that will actually write the attribute. 
Part of the fix for https://github.com/aspnet/dnx/issues/1504

Set the file version environment variable

---

build/BuildEnv.shade

I was asked by the authority (@Eilon) to add the year information in the file version even if that gives us only 7 years of versions.
So now it is: `<years since 2015 (1 digit) +1 > <current month (2 digits)> <current day (2 digits)>`
@joeloff

New assembly file version (with year)

---

makefile.shade

The cross plat CI fails because it tries to build projects that were not cloned.
@Eilon I would like to check this in for beta4
@pranavkm please review

Skip projects that were not cloned

---

build/_git.shade

I use a `git.cmd` that launches git, because I store it in my OneDrive to allow updating. In order to launch it, we have to use `cmd /C` :(. This changes our `git` task to do that
/cc @lodejard

change to use cmd to launch git on Windows

---

build/BuildEnv.shade
build/_k-standard-goals.shade
build/_kpm-build.shade
build/_kpm-pack.shade

Add support for `dnu build src/**`. Unless a particular environment variable is set, the build will still work as it does today so this change is not breaking and should not impact anything.

Build projects in one go

---

build-template/build.cmd
build/BuildEnv.shade
build/_bower.shade
build/_git.shade
build/_grunt.shade
build/_k-restore.shade
build/_k-standard-goals.shade
build/_k-test.shade
build/_k.shade
build/_kpm-build.shade
build/_kpm-pack.shade
build/_kpm-publish.shade
build/_node-install.shade
build/_rimraf.shade
makefile.shade

- hits all of the checkboxes in #272
Specify test runtime explicitly and support testing w/ DNX Core on Linux
- turn on DNX Core on Linux testing with `--test-dnxcore` target
- or `KOREBUILD_TEST_DNXCORE` environment variable
Work around aspnet/dnx#2566
- builds fail with DNX Core on Linux otherwise
Do not attempt to install nodejs if not on Windows
Use user's `default` DNVM when `%SKIP_DNX_INSTALL%` defined on Windows
- enables builds with DNX Core
- should be the default for new repos; older repos can opt in
Use consistent case for all `--quiet` environment variables
- also name these variables consistently; start w/ `KOREBUILD_`
- environment variables are case-sensitive on Linux and mixed case was annoying
- also get rid of leading space in these environment variable values
Check …

Support building with Core CLR (on Linux)

---

makefile.shade

Mono has inconsistent behavior in Process.Start (which is what Exec calls). Consider this directory structure
base
base/build.sh
base/sub
base/sub/build.sh
If $PWD is base and we call Process.Start with ProcessStartInfo { FileName = "build.sh", WorkingDirectory = "sub" }, the expected behavior (i.e. what .NET does on Windows) is that base\sub\build.sh would get started with a working directory of base/sub. However, base/build.sh gets called instead. For whatever reason, the same does not happen when trying to start a binary executable.
Because of this behavior, the universe build is broken on Linux. After change d679c85aa386f00afde6ce7062f286dedb76c7f9, the universe build.sh script does not get KoreBuild anymore and all builds fail because universe/build.sh is being called instead of …

Call correct build.sh when building repos.

---

build/_k-restore.shade

- infrastructure for switching restores everywhere i.e. addressing #290
- e.g. add `KOREBUILD_DNU_RESTORE_CORECLR` setting to `.travis.yml` files, especially if using Trusty

Support restoring with .NET Core

---

build/_k-standard-goals.shade

Removing the placeholder project in https://github.com/aspnet/ServerTests/pull/14 broke our CI. This is because nothing was built and the nuget-install step tries to publish from the non-existent `artifacts/build` directory. I'm thinking that the easiest fix is to just check for the existence of the build directory for nuget-install, thoughts? Is there a way for me to verify this fixes the issue before merging the PR?
@pranavkm @victorhurdugaci @rynowak

Adding directory existence check for nuget-install

---

KoreBuild-dotnet/build/_dotnet-test.shade
build/_k-test.shade

This change will enable us to run tests on CoreCLR on the CI.
cc @muratg @Eilon @victorhurdugaci

Skip tests on Mono if KOREBUILD_TEST_SKIPMONO is set.

---

KoreBuild-dotnet/build/_k-standard-goals.shade

Because dotnet dumps file on disk and removes them, the parallel build doesn't work anymore since files are locked. Thus, I'm removing the `--parallel` flag
FYI @pranavkm @NTaylorMullen

Remove the --parallel flag in KoreBuild-dotnet

---

KoreBuild-dotnet/build/_dotnet-build.shade
KoreBuild-dotnet/build/_k-standard-goals.shade

Compile requires all dependencies in the output folder. Build will build the dependencies.
Use build for samples.
cc @pranavkm

Build instead of compile for samples

---

KoreBuild-dotnet/build/_xunit-test.shade

Nothing needs to be done for `KOREBUILD_TEST_DNXCORE` since the new build doesn't skip tests on CoreCLR on non-Windows platforms.
#353
cc @victorhurdugaci

Honor KOREBUILD_TEST_SKIPMONO (#353).

---

KoreBuild-dotnet/build/KoreBuild.cmd
KoreBuild-dotnet/build/KoreBuild.sh
KoreBuild-dotnet/build/dotnet-install.ps1
KoreBuild-dotnet/build/dotnet-install.sh

/cc @victorhurdugaci @davidfowl 
This is using the install script from https://github.com/dotnet/cli/pull/1228 optimistically :). If that gets changed before merging I'll update it here.
Both scripts default the `CHANNEL` value to `beta`. But it can be overridden by an environment variable (`CHANNEL` ;))

update dotnet-install script and use beta channel

---

KoreBuild-dotnet/build/_dnx-test.shade
KoreBuild-dotnet/build/_k-standard-goals.shade

- new `--no-restore` pseudo-target controls whether `dotnet restore` runs at all
- `--quiet` adds `--verbosity minimal` to `dotnet restore` command
nit: clean out dangling `KOREBUILD_TEST_DNXCORE` environment variable
- `--test-dnxcore` now logs a warning

Add `--no-restore` and apply `--quiet` to `dotnet restore`

---

makefile.shade

* Avoid downloading the .build directory
cc @victorhurdugaci

* Use shallow clone when cloning on the CI

---

makefile.shade

cc @victorhurdugaci  \ @muratg . We'll trigger it off of DNX and eventually stop building it. I'll follow up with a change to Coherence to pick up this package in addition to UniverseCoherence.

Remove aspnet.xunit from Universe builds

---

makefile.shade

Part of #304.
Still needs a bit more testing.
cc @victorhurdugaci @pranavkm

Cache Coherence locally in ci-test.

---

makefile.shade

- Read all environment variables at the top
- `camelCase` variables names instead of `LIKE_THIS`
- Reasonable defaults
- Only try to cache Coherence if the share exists
cc @victorhurdugaci

Several refactorings in makefile.shade.

---

makefile.shade

Will revert when https://github.com/NuGet/Home/issues/2383 is fixed.
cc @victorhurdugaci @pranavkm

Temporary: Don't expand packages when caching Coherence on non-Windows.

---

makefile.shade

Allow a 'Gate branch' which is built instead of dev if it exists. The point of this is to prevent breaking changes made for changes in CoreFX packages from blocking people until the CoreCLR build passes and makes those available.
CC @pranavkm @victorhurdugaci

Allow a 'Gate branch' which is built instead of dev if it exists

---

makefile.shade

`sync-commits` fails when some repos were skipped because `UNIVERSE_SKIP_NO_CREDENTIALS` was set.
cc @victorhurdugaci

Only reset repos that were cloned.

---

global.json

Required to make partner package mirroring work.

Explicitly specify the version of the CLI

---

graph.proj
makefile.shade

Workaround https://github.com/Microsoft/msbuild/issues/1587
Required before we upgrade to RC.3

Workaround issue in solution targets in MSBuild RC3

---

makefile.shade

We removed "KOREBUILD_ADD_ASSEMBLY_INFO", but it is still useful to the collect the commits artifact file.

Collect commit files from artifacts directory

---

build/RepositoryBuild.targets

- avoids MSBuild continuing past failed repositories in sequential builds
- ignored when building in parallel (unfortunately)

`StopOnFirstFailure` when doing repository builds

---

.gitignore
build.ps1
build.sh
build/RepositoryBuild.targets
build/repo.targets
version.xml

Changes the bootstrappers to use the "compiled" KoreBuild. Part of https://github.com/aspnet/KoreBuild/issues/258
This will also override the build.cmd/build.sh in individual repos to use the build.ps1 in the Unverse repo. This is temporary until we've updated all individual repos to use the new bootstrapper.

Change bootstrapper to install the compiled version of KoreBuild

---

build/repo.targets
build/tasks/BuildGraph/DependencyGraphSpecProvider.cs
build/tasks/BuildGraph/Repository.cs

The build graph computation was ignoring the ExcludeSolutions item group. For repos with multiple solutions like EF and Mvc, this can cause incorrect an repo graph calculation if the excluded solution has PackageReferences that violate the build graph chain.

Respect ExcludeSolutions when calculating the build graph

---

build/RepositoryBuild.targets
build/dependencies.props
build/repo.props
build/repo.targets
build/repobuild/AfterKoreBuild.targets
build/repobuild/BeforeKoreBuild.props
build/tasks/BuildGraph/DependencyGraphSpecProvider.cs
build/tasks/BuildGraph/GraphBuilder.cs
build/tasks/BuildGraph/GraphNode.cs
build/tasks/BuildGraph/Project.cs
build/tasks/BuildGraph/Repository.cs
build/tasks/BuildGraph/TopologicalSort.cs
build/tasks/CalculateBuildGraph.cs
build/tasks/RepoTasks.csproj
build/tasks/VersionPinning/PinVersionUtility.cs
lineups/Internal.AspNetCore.Universe.Lineup.nuspec

Part of https://github.com/aspnet/KoreBuild/issues/239
This will produce a "lineup" package containing a list of all packages produced in the universe build, along with a few other external dependencies.
Example result:
[Internal.AspNetCore.Universe.Lineup.2.1.0-preview1-t004e82595.nupkg.zip](https://github.com/aspnet/Universe/files/1216125/Internal.AspNetCore.Universe.Lineup.2.1.0-preview1-t004e82595.nupkg.zip)
cc @mikeharder @ryanbrandenburg

Produce a lineup package containing all Universe packages (plus a few others)

---

build/dependencies.props

Also, expands the list of xunit packages to include commonly used sub-packages, such as xunit.core.

Upgrade xunit to 2.3.0-beta4

---

build/dependencies.props

This includes almost everything referenced from an ASP.NET Core project using the versions as they currently stand in the dev branch.
There are a few to be added for a few repos that have special considerations, such as EF (needs to reference EF Core 1.x) and EF/MVC/Scaffolding (they reference roslyn packages). I'll address those later when we convert those repos to lineups.
cc @Eilon - you may be interested in seeing this list...

Expand the list of external dependencies 

---

build/repo.targets
build/tasks/ReadPackageDependencies.cs
build/tasks/ReadPackageIdentity.cs
build/tasks/RepoTasks.tasks

The difference between this one and #545 is that this one won't duplicate other lineups into the universe lineup file. This is necessary for now until we can merge to one master lineup.
Changes:
This merges pre-existing packages from previous builds of Universe with the list of packages to be produced in the current run.
Pre-existing packages are expected to be in .deps/build/ and are expected to have only one version of a package id in that folder.
This also requires any additional lineups to be in .deps/lineups/ so they can be filtered from the Internal.AspNetCore.Universe.Lineup file.
Fixes https://github.com/aspnet/Universe/issues/546

Support partial-graph builds - take 2

---

build/tasks/CalculateBuildGraph.cs

- still must build entire Universe locally before using `$(BuildGraphOf)`

Fix `First()` failure when `$(BuildGraphOf)` is set

---

build/dependencies.props

These two packages are dependencies of `Microsoft.VisualStudio.Editor` but need to be used explicitly in the lineup.

Add Microsoft.VisualStudio.Text.Data and UI to the universe lineup.

---

build/dependencies.props
build/repo.targets
build/tasks/CopyPackagesToSplitFolders.cs
build/tasks/DownloadNuGetPackages.cs
build/tasks/Logger/MSBuildLogger.cs
build/tasks/RepoTasks.csproj
build/tasks/RepoTasks.tasks
build/tasks/Utilities/PackageCategory.cs
build/tasks/Utilities/PackageCollection.cs

Follow up to #561 
Changes:
- Ensures external dependencies are available on the feed specified
- Packages marked as 'Mirror=true' end up in the `artifacts/mirror/` folder so we can clone them to our mirror.
FYI this is a lead up to the next step, which is to make NuGet restore on projects hermetic by restricting access to any NuGet feed other than those specified in dependencies.props.

Mirror external dependencies

---

build/RuntimeStore.targets
build/artifacts.props
build/dependencies.props
build/tasks/AddRSReferences.cs
build/tasks/RepoTasks.tasks
build/tasks/ResolveHostingStartupPackages.cs
build/tools/templates/RS.Manifest/RS.Manifest.csproj
build/tools/templates/RS.References/RS.References.csproj

There is a lot of code duplication here. For example BuildAllMetapackage and BuildRSReferencePackage targets uses mostly the same logic and can be cleaned up. Same with the Add*References.cs build tasks. This change will also allow us to avoid building then unpacking and repacking the .All metapackage. These changes will follow in a cleanup PR later (I'll file an issue) but I want to do the minimal amount of required work for now to get the builds running.

Produce separate reference package for runtime store generation

---

build/dependencies.props
korebuild-lock.txt

This update includes a 2.1 runtime.
Blocked on https://github.com/aspnet/Routing/pull/490 - cc @rynowak @Eilon

Updating BuildTools to 2.1.0-preview1-15557

---

build/dependencies.props

This is required for https://github.com/aspnet/Hosting/pull/1189

Update ServiceController version for netstandard support

---

build/external-dependencies.props

cc @dagood 
Other assets, not just those from dotnet-core/roslyn, may come from DotNetAdditionalRestoreSources  in an orchestrated build

Set DotNetAdditionalRestoreSources on all ExternalDependency items

---

.vscode/settings.json
build/SharedFx.targets
build/Templating.targets
build/external-dependencies.props
build/repo.props
build/repo.targets
korebuild-lock.txt

Output of sharedfx build now matches expected blob store layout
```
<root>/Runtime/$(PackageVersion)/aspnetcore-runtime-$(PackageVersion)-$(Rid).zip
<root>/Runtime/$(PackageVersion)/aspnetcore-runtime-$(Rid)-version-badge.svg
<root>/Runtime/$(PackageVersion)/latest.aspnetcore.version
```
Other changes
- Upgrade build tools
- Produce an SVG badge for the sharedfx
- Produce the 'latest.aspnetcore.version' file for the dotnet-install.ps1/sh downloader script
- Change layout of output for sharefx build
- Use KoreBuild's bundled package folder for internal build tools packages
cc @javiercn 
cc @jkotalik - includes https://github.com/aspnet/BuildTools/commit/c390edb6f73e3ab992402835c004414c1fadfd4a

Change output of sharedfx build to match feed layout

---

build/SharedFx.props
build/SharedFxInstaller.targets

Spoke with @muratg and @DamianEdwards and it seems like I misunderstood the requirements for hosting 2.0 apps. It is expected that 2.1 and 2.0 will be installed side by side and 2.0 must be installed to host 2.0 apps. This means we should not add a dependency of 2.0 runtime store in the 2.1 shared framework installers.

Remove 2.0 runtime store dependency from 2.1 shared framework installers

---

build/SharedFx.props
build/SharedFx.targets

From our email discussions, it seems like we would rather use platform_assemblies_paths instead of app_paths though theoretically they should be equivalent in our use case.

Use platform assemblies paths instead of app paths for crossgen

---

build/artifacts.props

Remove Dispatcher packages

---

src/Microsoft.AspNetCore.All/Microsoft.AspNetCore.All.csproj
src/Microsoft.AspNetCore.All/build/netcoreapp2.1/Microsoft.AspNetCore.All.targets

Last work item in https://github.com/aspnet/Universe/issues/662.
I'm wondering if we should backport this to the 2.0 metapackage and make it only compatible with netcoreapp2.0. 
I'm adding an initial target that should be run before build or publish. Is there a better approach?

Add TFM compatibility check to 2.1 metapackage

---

build/tools/docker/rhel.7/Dockerfile

We need this to fix our shared fx installer builds. Changes are the same as dotnet/cli#8151.
fyi @muratg @Eilon since it's ask mode, note this is only affecting build infrastructure.

Update rhel.7 image used to build rpms

---

build/Publish.targets
build/SharedFx.targets
build/Templating.targets
src/Directory.Build.targets

`/t:GetFilesToPublish` is missing packages to publish that don't come from the standard repo build.
Adds
- ArtifactInfo items for metapackages and templates packages
- a build error if there isn't a one to one mapping of ArtifactInfo to PackageArtifact items

Ensure all packages are included in ArtifactInfo

---

build/artifacts.props

This should fix the VSTS issue 555879 where SpaServices.Extensions is missing from the offline scenarios.

Include SpaServices.Extensions in .App and .All metapackages

---

build/dependencies.props
build/external-dependencies.props

Forward port from patch to dev: https://github.com/aspnet/Universe/pull/844. This preps for forward porting the new WsFed package in Security.

Raise IdentityModel dependencies to 5.2.0. Add new WsFed dependencies.

---

build/artifacts.props

Forgot to include the .App metapackage to the LZMA after removing it as a dependency of .All in https://github.com/aspnet/Universe/pull/837. This broke offline scenarios where templates are now using .App as the default metapackage.
cc @DamianEdwards @Eilon as this is required for preview1.

Include Microsoft.AspNetCore.App in the LZMA

---

build/Publish.targets
build/artifacts.props
build/repo.props
build/repo.targets
build/tasks/AnalyzeBuildGraph.cs
korebuild.json

When builds of package succeed, but the runtime fails to build, we can end up in state where the lineup package on myget is newer than the available shared runtime.
This delays publishing until we have _everything_ built. It also aligns closer with how we publish for prodcon builds.
Corresponding change to coherence-signed:  https://github.com/aspnet/Coherence-Signed/pull/769
depends on https://github.com/aspnet/SignalR/pull/1416

Fix #785 - publish nuget packages and the shared runtime at the same time

---

build/Publish.targets
build/external-dependencies.props

Resolves https://github.com/aspnet/Universe/issues/892
This will push the following packages from corefxlab into prodcon output, and eventually, to nuget.org.
- System.Buffers.Primitives
-  System.IO.Pipelines
- System.Text.Encodings.Web.Utf8
- System.Text.Primitives
For preview1 only! This should be reverted for preview2 as these packages should be coming from dotnet/corefx. Using #893 to ensure this is reverted.
cc @muratg @ahsonkhan @pakrym @dagood @mmitche @joshfree

[2.1-preview1] Publish corefxlab packages to the transport feed

---

build/artifacts.props

Spoke to @anurse online and he believes msgpack support should not be in the .All metapackage.
FYI @DamianEdwards

Remove MsgPack from .All metapackage

---

build/artifacts.props

Addresses #936 
Removing two azure packages:
Microsoft.AspNetCore.AzureAppServicesIntegration
Microsoft.Extensions.Logging.AzureAppServices

Remove azure packages from .App metapackage and framework

---

build/external-dependencies.props

Addresses https://github.com/aspnet/MetaPackages/issues/260.
I tested building the metapackage and building the shared framework locally on macOS.
This adds System.Net.Http.Formatting.dll to the .App shared framework.
cc @DamianEdwards @glennc @rynowak @davidfowl

Add Microsoft.AspNet.WebApi.Client to .App and .All metapackages

---

build/tools/templates/SharedFxSymbols/SharedFrameworkSymbols.nuspec

When we used the updated cli, the behaviour of globbing inside nuspec files changed. Currently we include the symbols files twice, once by globbing in MSBuild and once by globbing in the nuspec. The globbing in MSBuild is consistent and will return 
```
Packing C:\gh\Universe\.w\Symbols\Microsoft.AspNetCore.All\runtimes\win-x64\lib\netcoreapp2.1\Microsoft.Azure.KeyVault.dll => runtimes\win-x64\lib\netcoreapp2.1\Microsoft.Azure.KeyVault.dll
```
This was the same path produced by globbing in the nuspec which is why our builds previously only included the files once in the final symbols nupkg.
However, in the updated CLI, the globbing pattern in the nuspec started to return results like:
```
Packing C:\gh\Universe\.w\Symbols\Microsoft.AspNetCore.All\\runtimes\win-x64\lib\netcoreapp2.1\Microso …
```

Remove duplicate files from symbols packages

---

build/PackageArchive.targets
build/dependencies.props
build/tasks/CreateLzma.cs
build/tasks/RepoTasks.csproj
build/tasks/RepoTasks.tasks

Addresses https://github.com/aspnet/Universe/issues/595. This removes our dependency on the published archiver executable currently on the drop share. Note that this depends on https://github.com/dotnet/dotnet-cli-archiver/pull/11 being merged to work.

Add lzma repo task

---

build/RuntimeStoreInstaller.targets

These are the new installer platforms required for the April patches.
Remove ubuntu 17.04
Add ubuntu 17.10
Add ubuntu 18.04

Update supported installer platforms

---

build/Publish.targets
build/SharedFx.props
build/SharedFx.targets
build/repo.props

Latest ProdCon build was not publishing symbols for the sharedfx or packages.
Changes:
- update build tools to ensure symbols packages from repos are included
- add package info for sharedfx symbols nupkgs
Here is a complete list of all files expected to exist during publishing. 
https://gist.github.com/natemcmaster/5ae280dd41efe44efa7b603fb4198433

Include symbols in published output

---

.gitmodules
build/Publish.targets
build/SharedFx.props
build/SharedFx.targets
build/artifacts.props
build/repo.props
build/repo.targets
build/submodules.props
korebuild-lock.txt

Bring changes back into dev from 2.1. This includes the addition of a new submodule, AADIntegration.
@javiercn I will wait until you have the dev branch of AADIntegration ready to go first. I could merge as is, but the update automation would immediately have trouble with this because dev currently is behind release/2.1 in aspnet/AADIntegration

Merge release/2.1 into dev

---

build/SharedFx.targets
build/artifacts.props
src/Microsoft.AspNetCore.All/runtime.json.in
src/Microsoft.AspNetCore.App/Microsoft.AspNetCore.App.csproj
src/Microsoft.AspNetCore.App/runtime.json.in
src/runtime.win.Microsoft.AspNetCore.All/runtime.win.Microsoft.AspNetCore.All.csproj
src/runtime.win.Microsoft.AspNetCore.App/runtime.win.Microsoft.AspNetCore.App.csproj

#762 Tested the scenarios outlined in the issue, specifically:
- portable restore does not have Microsoft.AspNetCore.Server.IIS in project.assets.json
- RID specific restore (tested win-x64, win-x86) has Microsoft.AspNetCore.Server.IIS in project.assets.json
- Standalone publish with win-x64 has aspnetcorerh.dll in the output
- Standalone publish with linux-x64 does not have aspnetcorerh.dll in the output

Build runtime specific metapackages

---

build/repo.targets
version.props

Reduce the number of places we have to manually update to keep our installers consistent with the runtime.

Generate branding.g.props for use in downstream builds that need to align version information

---

build/dependencies.props
build/external-dependencies.props

Generate additional dependency information for downstream consumption by Windows installer builds.

[2.0.x] Add ANCM version to generate list of deps versions

---

build/artifacts.props

Let's take a closer look at https://github.com/aspnet/Universe/commit/d8f190561432ef9dce5b2fef16349d8ff1a321fd.
Currently Microsoft.AspNetCore.App is missing from the LZMA in preview2 but was there in preview1. There were a few reverts and merges around these changes and we ended up with the wrong set of changes in release/2.1. This is currently breaking VS new template tests run by the vendors.

Add .App metapackage to the LZMA

---

build/artifacts.props

Two SignalR packages related to MessagePack are being removed.
Wait until https://github.com/aspnet/SignalR/pull/1830 is merged before merging this PR.

Remove two SignalR MessagePack packages

---

build/repo.targets

Publish failed because it was looking for `Internal.AspNetCore.Universe.Lineup.2.1.0-preview2-30569+pb-20180405-07.nupkg`, but the actual file name is `Internal.AspNetCore.Universe.Lineup.2.1.0-preview2-30569.nupkg`. Change the variables used because NuGet strips the `+` metadata when producing .nupkg files.

Use PackageVersion to define version of the LineupPackage

---

build/RuntimeStore.targets
build/artifacts.props

When we produce a new hosting startup additionalDeps file without a new version of Microsoft.NETCore.App, build currently fails due to a conflict in file path.
> The file '/mnt/work/71ae3284d35ddee4/.w/additionalDeps/Microsoft.AspNetCore.ApplicationInsights.HostingStartup/shared/Microsoft.NETCore.App/2.0.7/Microsoft.AspNetCore.ApplicationInsights.HostingStartup.deps.json' already exists.
This resolves the conflict by skipping inclusion of additionalDeps files in 2.0.8.
FYI @muratg

Exclude additionalDeps files due to file path conflicts with the 2.0.7 release

---

README.md
build/SharedFx.props
build/dependencies.props
build/repo.props
scripts/UpdateDependenciesCoreFx.ps1

React to https://github.com/dotnet/core-setup/pull/4062
Part of #1101. This PR currently only applies to the 'dev' branch. When core-setup backports https://github.com/dotnet/core-setup/pull/4062  to their 2.1 branches, I'll backport this change too too.
cc @weshaggard

Remove alpine.3.6-x64 builds

---

build/SharedFx.props
build/SharedFxInstaller.targets
build/repo.props
version.props

Addresses #1116 
Now produces these new upgradeable installers with the same naming scheme as https://github.com/dotnet/core-setup/pull/4020/:
- aspnetcore-runtime-2.1.0-rtm-12345-x64-upgrade.deb
- aspnetcore-runtime-2.1.0-rtm-12345-x64-upgrade.rpm
- aspnetcore-runtime-2.1.0-rtm-12345-rh.rhel.7-x64-upgrade.rpm
Note that I'm temporarily continuing to produce the non-upgradeable installers as well. This allows CLI builds to continue working while they react to our changes and switch to producing upgradeable installers.
Testing

Build upgradeable installers

---

build/tools/templates/Archive/Archive.csproj
build/tools/templates/SharedFx/SharedFx.csproj

Should fix the sharedfx builds.

Allow targetting of netcoreapp2.2 for sharedfx and lzma

---

build/external-dependencies.props

- should improve `UpgradeDependencies` at least in MVC repo
- hopefully will also correct build break in Update Universe builds

Give BenchmarksOnly* `<ExternalDependency>`s `VariableName` metadata

---

Directory.Build.props
Directory.Build.targets
Microsoft.AspNetCore.sln
build/SharedFx.targets
build/common.props
build/dependencies.props
build/tasks/RepoTasks.csproj
build/tools/templates/Archive/Archive.csproj
build/tools/templates/SharedFx/SharedFx.csproj
src/Directory.Build.props
src/Microsoft.AspNetCore.All/Microsoft.AspNetCore.All.csproj
src/Microsoft.AspNetCore.Analyzers/Microsoft.AspNetCore.Analyzers.csproj
src/Microsoft.AspNetCore.App/Microsoft.AspNetCore.App.csproj
test/SharedFx.UnitTests/AssertEx.cs
test/SharedFx.UnitTests/SharedFx.UnitTests.csproj
test/SharedFx.UnitTests/SharedFxTests.cs
test/SharedFx.UnitTests/TestData.cs
test/SharedFx.UnitTests/TestDataAttribute.cs
version.props

I've cherry-picked https://github.com/aspnet/Universe/pull/1201 back to release/2.1. I'm doing this now to lay the foundation for tests I want to add as a part of building a fix for #1192.
Changes:
* Add a test project with simple unit tests for the shared framework
* Add root-level Directory.Build.props/targets files
* Cleanup .csproj files to reduce duplication

[2.1]: Add unit tests for the shared framework (backport) 

---

build/tasks/CreateLzma.cs

To be doubly sure the LZMA generated doesn't have missing characters, we can trim trailing slashes in our build tasks as well. This should unblock 2.1.3 prodcon builds and needs to go into release/2.2 and master as well.

Ensure no trailing slashes for LZMA generation

---

.gitmodules
build/artifacts.props
build/buildorder.props
build/submodules.props
modules/SubmoduleGraph.dgml

Per email thread, we'll keep WebHooks building in master, but we'll remove it for now from 2.2. We can re-add later as we nail down the shipping schedule.

Remove aspnet/WebHooks from release/2.2

---

build/dependencies.props

- update our own NuGet packages to align lower-level dependencies

Use OSS package versions consistent with aspnet/benchmarks and Microsoft.AspNetcore.All 2.1.2
